-- Seed destinations
INSERT INTO destinations (id, title, edition, description, price, country, vibe, img, steps, is_active) VALUES
('amalfi', 'Amalfi Coast', 'Edition 01 // Positano', 'Cliffside calm on the Mediterranean', 4200, 'Italy', 'Serenity', 'https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&q=80&w=600', '["Arrive at Naples International Airport", "Private transfer to Positano villa", "Welcome dinner on the terrace", "Day trip to Capri by boat", "Cooking class with local chef", "Departure transfer"]', true),
('alps', 'Swiss Alps', 'Edition 02 // Zermatt', 'Peak silence above the clouds', 4800, 'Switzerland', 'Majesty', 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&q=80&w=600', '["Arrive at Zurich Airport", "Scenic train to Zermatt", "Chalet check-in with mountain view", "Guided hike to alpine lake", "Helicopter glacier tour", "Fondue dinner in mountain hut", "Departure"]', true),
('kyoto', 'Kyoto', 'Edition 03 // Higashiyama', 'Ancient ritual in moss and gold', 3900, 'Japan', 'Heritage', 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&q=80&w=600', '["Arrive at Kansai International Airport", "Bullet train to Kyoto", "Ryokan check-in with tea ceremony", "Golden Pavilion morning visit", "Bamboo grove walk at dawn", "Private kaiseki dinner", "Zen meditation session"]', true),
('dolomites', 'Dolomites', 'Edition 04 // Alta Badia', 'Rose-tipped peaks at dawn', 4500, 'Italy', 'Adventure', 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&q=80&w=600', '["Arrive at Venice Airport", "Drive to Alta Badia", "Mountain lodge check-in", "Via ferrata guided climb", "Sunrise hike to Lagazuoi", "Wine tasting in local vineyard", "Departure"]', true),
('santorini', 'Santorini', 'Edition 05 // Oia', 'Blue domes and endless sunsets', 4400, 'Greece', 'Serenity', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&q=80&w=600', '["Arrive at Santorini Airport", "Private transfer to Oia suite", "Sunset cocktail on caldera", "Catamaran cruise to volcano", "Wine tour across the island", "Farewell dinner with sunset view"]', true),
('iceland', 'Iceland', 'Edition 06 // Reykjavik', 'Fire and ice under the aurora', 5200, 'Iceland', 'Wild', 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&q=80&w=600', '["Arrive at Keflavik Airport", "Blue Lagoon geothermal soak", "Northern lights hunt", "Glacier hike on Vatnajokull", "Golden Circle tour", "Ice cave exploration", "Departure"]', true),
('marrakech', 'Marrakech', 'Edition 07 // Medina', 'Medina mysteries in terracotta', 3600, 'Morocco', 'Heritage', 'https://images.unsplash.com/photo-1597212618440-806262de4f6b?auto=format&fit=crop&q=80&w=600', '["Arrive at Marrakech Airport", "Riad check-in in Medina", "Jemaa el-Fna evening exploration", "Atlas Mountains day trip", "Private hammam and spa", "Cooking class in traditional riad"]', true),
('banff', 'Banff', 'Edition 08 // Banff', 'Turquoise lakes and pine silence', 4900, 'Canada', 'Serenity', 'https://images.unsplash.com/photo-1508737804141-4c3b688e2548?auto=format&fit=crop&q=80&w=600', '["Arrive at Calgary Airport", "Scenic drive to Banff", "Lake Louise canoe adventure", "Banff Gondola ride", "Wildlife photography tour", "Hot springs relaxation"]', true),
('patagonia', 'Patagonia', 'Edition 09 // Torres del Paine', 'Wind-carved frontiers of granite', 5600, 'Argentina', 'Adventure', 'https://images.unsplash.com/photo-1516307365426-bea591f05011?auto=format&fit=crop&q=80&w=600', '["Arrive at Santiago Airport", "Flight to Punta Arenas", "W trek guided expedition", "Grey Glacier kayaking", "Horseback riding estancia", "Stargazing in Torres del Paine"]', true),
('queenstown', 'Queenstown', 'Edition 10 // Queenstown', 'Thrill meets alpine stillness', 4700, 'New Zealand', 'Adventure', 'https://images.unsplash.com/photo-1508193638397-1c4234db14d8?auto=format&fit=crop&q=80&w=600', '["Arrive at Queenstown Airport", "Lakeside lodge check-in", "Milford Sound cruise", "Bungee jumping at Kawarau Bridge", "Wine tour in Gibbston Valley", "Onsen hot tub with lake view"]', true),
('bali', 'Bali', 'Edition 11 // Ubud', 'Temples at dawn, rice at dusk', 3800, 'Indonesia', 'Serenity', 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&q=80&w=600', '["Arrive at Ngurah Rai Airport", "Private villa in Ubud", "Tegallalang rice terrace walk", "Temple purification ritual", "Sunset at Uluwatu", "Balinese massage and spa"]', true),
('provence', 'Provence', 'Edition 12 // Luberon', 'Lavender fields and golden light', 4100, 'France', 'Serenity', 'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&q=80&w=600', '["Arrive at Marseille Airport", "Luberon village stay", "Lavender fields photography", "Wine tasting in Châteauneuf-du-Pape", "Market tour and cooking class", "Hot air balloon ride"]', true),
('maldives', 'Maldives', 'Edition 13 // North Atoll', 'Overwater solitude in endless blue', 5800, 'Maldives', 'Escape', 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&q=80&w=600', '["Arrive at Malé Airport", "Seaplane to resort", "Overwater villa check-in", "Snorkeling with manta rays", "Sunset dolphin cruise", "Underwater restaurant dinner"]', true),
('tuscany', 'Tuscany', 'Edition 14 // Chianti', 'Rolling vineyards and golden hills', 4400, 'Italy', 'Serenity', 'https://images.unsplash.com/photo-1467269204594-9661b134dd2b?auto=format&fit=crop&q=80&w=600', '["Arrive at Florence Airport", "Villa check-in in Chianti", "Wine tasting tour", "Truffle hunting experience", "Florence art and culture day", "Cooking class at the villa"]', true),
('seychelles', 'Seychelles', 'Edition 15 // Indian Ocean', 'Granite boulders and turquoise waters', 6800, 'Seychelles', 'Escape', 'https://images.unsplash.com/photo-1583417319070-4a69db38a482?auto=format&fit=crop&q=80&w=600', '["Arrive at Seychelles Airport", "Private island transfer", "Beach villa check-in", "Snorkeling at Anse Lazio", "Nature hike in Vallée de Mai", "Catamaran sunset cruise"]', true),
('paris', 'Paris', 'Edition 16 // City of Light', 'Romance at every corner', 3600, 'France', 'Heritage', 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&q=80&w=600', '["Arrive at Charles de Gaulle Airport", "Le Marais apartment check-in", "Louvre private tour", "Eiffel Tower sunset picnic", "Seine river cruise", "Patisserie workshop"]', true),
('venice', 'Venice', 'Edition 17 // Serenissima', 'Canals and timeless elegance', 4100, 'Italy', 'Heritage', 'https://images.unsplash.com/photo-1440588527744-c5b3d2ed0c7a?auto=format&fit=crop&q=80&w=600', '["Arrive at Marco Polo Airport", "Water taxi to hotel", "St. Marks Basilica tour", "Gondola sunset ride", "Murano glass workshop", "Hidden canal walking tour"]', true),
('costa-rica', 'Costa Rica', 'Edition 18 // Pura Vida', 'Rainforest meets volcano and surf', 3600, 'Costa Rica', 'Adventure', 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&q=80&w=600', '["Arrive at San Jose Airport", "Cloud forest lodge", "Arenal Volcano hike", "Zip-lining through canopy", "Pacific coast surf lesson", "Wildlife night tour"]', true),
('nepal', 'Nepal', 'Edition 19 // Himalayan Dawn', 'Himalayan majesty and ancient temples', 3400, 'Nepal', 'Adventure', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&q=80&w=600', '["Arrive at Kathmandu Airport", "Heritage hotel check-in", "Everest scenic flight", "Patan Durbar Square tour", "Himalayan sunrise hike", "Meditation retreat"]', true),
('mozambique', 'Mozambique', 'Edition 20 // Coastal Wild', 'Indian Ocean reefs and dhow sails', 4800, 'Mozambique', 'Escape', 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&q=80&w=600', '["Arrive at Maputo Airport", "Coastal lodge check-in", "Dhow sailing trip", "Snorkeling on coral reefs", "Island beach picnic", "Seafood feast on the shore"]', true),
('big-sur', 'Big Sur', 'Edition 21 // Pacific Coast', 'Where mountains meet the Pacific', 3200, 'USA', 'Wild', 'https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&q=80&w=600', '["Arrive at Monterey Airport", "Highway 1 road trip", "McWay Falls hike", "Nepenthe sunset dinner", "Elephant seal viewing", "Redwood forest meditation"]', true),
('sedona', 'Sedona', 'Edition 22 // Red Rock', 'Red rock vortex sanctuary', 2900, 'USA', 'Serenity', 'https://images.unsplash.com/photo-1505533542167-8c89838bb19f?auto=format&fit=crop&q=80&w=600', '["Arrive at Flagstaff Airport", "Red rock villa check-in", "Cathedral Rock hike", "Vortex meditation session", "Jeep tour of canyons", "Sunset yoga on the rocks"]', true),
('norway', 'Norwegian Fjords', 'Edition 23 // Fjord Peace', 'Deep blue fjords and aurora skies', 5600, 'Norway', 'Wild', 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&q=80&w=600', '["Arrive at Bergen Airport", "Fjord cruise to Flåm", "Stave church visit", "Aurora borealis chase", "Glacier hiking adventure", "Arctic wildlife safari"]', true),
('sri-lanka', 'Sri Lanka', 'Edition 24 // Serendipity', 'Tea plantations and ancient fortresses', 2600, 'Sri Lanka', 'Heritage', 'https://images.unsplash.com/photo-1508193638397-1c4234db14d8?auto=format&fit=crop&q=80&w=600', '["Arrive at Colombo Airport", "Tea plantation bungalow", "Sigiriya Rock fortress climb", "Yala National Park safari", "Galle Fort walking tour", "Beach sunset dinner"]', true),
('azores', 'Azores', 'Edition 25 // Atlantic Garden', 'Volcanic craters and blue hydrangeas', 3100, 'Portugal', 'Wild', 'https://images.unsplash.com/photo-1508193638397-1c4234db14d8?auto=format&fit=crop&q=80&w=600', '["Arrive at Ponta Delgada Airport", "Crater lake villa", "Sete Cidades hike", "Whale watching expedition", "Hot springs soak", "Hydrangea trail photography"]', true),
('orlando', 'Orlando', 'Edition 26 // Family Magic', 'Theme parks and family magic', 4800, 'USA', 'Adventure', 'https://images.unsplash.com/photo-1508737804141-4c3b688e2548?auto=format&fit=crop&q=80&w=600', '["Arrive at Orlando Airport", "Resort check-in", "Magic Kingdom day", "Universal Studios adventure", "Pool and spa relaxation", "Character breakfast farewell"]', true),
('tokyo', 'Tokyo', 'Edition 27 // Future Tokyo', 'Neon lights and ancient temples', 5200, 'Japan', 'Heritage', 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&q=80&w=600', '["Arrive at Narita Airport", "Shinjuku hotel check-in", "Tsukiji market breakfast", "Senso-ji Temple visit", "Shibuya crossing night walk", "Robotics and anime district"]', true),
('dubai', 'Dubai', 'Edition 28 // Desert Oasis', 'Desert safaris and sky-high adventures', 5500, 'UAE', 'Adventure', 'https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&q=80&w=600', '["Arrive at Dubai International", "Palm Jumeirah resort", "Burj Khalifa sunset view", "Desert safari and dune bashing", "Gold souk and spice market", "Dubai Marina dinner cruise"]', true),
('barcelona', 'Barcelona', 'Edition 29 // Catalan Soul', 'Gaudi and Mediterranean joy', 3800, 'Spain', 'Heritage', 'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&q=80&w=600', '["Arrive at Barcelona Airport", "Gothic quarter apartment", "Sagrada Familia guided tour", "Park Güell morning walk", "La Boqueria market lunch", "Tapas and flamenco evening"]', true),
('cancun', 'Cancun', 'Edition 30 // Mayan Coast', 'Mayan ruins and Caribbean waters', 3400, 'Mexico', 'Escape', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&q=80&w=600', '["Arrive at Cancun Airport", "Hotel zone resort", "Chichen Itza day trip", "Cenote swimming adventure", "Isla Mujeres catamaran", "Beachfront farewell dinner"]', true),
('greek-islands', 'Greek Islands', 'Edition 31 // Aegean Family', 'Whitewashed villages and family shores', 4200, 'Greece', 'Serenity', 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&q=80&w=600', '["Arrive at Athens Airport", "Ferry to the islands", "Villa with private pool", "Family beach day", "Traditional village exploration", "Sunset sailing trip"]', true),
('mauritius', 'Mauritius', 'Edition 32 // Family Paradise', 'Coral reefs and sugar-sand beaches', 5100, 'Mauritius', 'Escape', 'https://images.unsplash.com/photo-1597212618440-806262de4f6b?auto=format&fit=crop&q=80&w=600', '["Arrive at Mauritius Airport", "Beach resort check-in", "Catamaran to Ile aux Cerfs", "Underwater waterfall helicopter", "Temple and botanical garden tour", "Spa and farewell dinner"]', true),
('cape-town', 'Cape Town', 'Edition 33 // Atlantic Edge', 'Table Mountain and Atlantic shores', 4000, 'South Africa', 'Adventure', 'https://images.unsplash.com/photo-1576485290814-1c72a0c5b3a8?auto=format&fit=crop&q=80&w=600', '["Arrive at Cape Town Airport", "Waterfront hotel check-in", "Table Mountain cableway", "Cape Peninsula drive", "Boulders Beach penguins", "Winelands tasting tour"]', true),
('zanzibar', 'Zanzibar', 'Edition 34 // Spice Island', 'Spice Island dreams and turquoise tides', 3500, 'Tanzania', 'Escape', 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&q=80&w=600', '["Arrive at Zanzibar Airport", "Stone Town boutique hotel", "Spice plantation tour", "Prison Island snorkeling", "Nungwi beach sunset", "Dhow sailing experience"]', true),
('nairobi-kenya', 'Nairobi', 'Edition 35 // Safari Capital', 'Safari capital beneath the African sun', 5000, 'Kenya', 'Adventure', 'https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&q=80&w=600', '["Arrive at JKIA Nairobi", "Luxury safari camp check-in", "Masai Mara game drive", "Giraffe sanctuary visit", "Great Rift Valley view", "Bush dinner under stars"]', true),
('egypt', 'Egypt', 'Edition 36 // Pharaohs Valley', 'Pyramids and pharaohs by the Nile', 4600, 'Egypt', 'Heritage', 'https://images.unsplash.com/photo-1539650116574-8efeb43e2750?auto=format&fit=crop&q=80&w=600', '["Arrive at Cairo Airport", "Pyramid view hotel", "Great Pyramid guided tour", "Nile felucca sunset sail", "Egyptian Museum exploration", "Khan El Khalili bazaar"]', true),
('bangkok', 'Bangkok', 'Edition 37 // Golden Temple', 'Golden temples and street food dreams', 2800, 'Thailand', 'Heritage', 'https://images.unsplash.com/photo-1508009603885-50cf7c579365?auto=format&fit=crop&q=80&w=600', '["Arrive at Suvarnabhumi Airport", "Riverside hotel check-in", "Grand Palace morning visit", "Floating market tour", "Street food exploration", "Thai massage and spa"]', true),
('phuket', 'Phuket', 'Edition 38 // Andaman Pearl', 'Limestone karves and Andaman sunsets', 3200, 'Thailand', 'Escape', 'https://images.unsplash.com/photo-1589394815804-964ed0be2eb5?auto=format&fit=crop&q=80&w=600', '["Arrive at Phuket Airport", "Beach resort check-in", "Phi Phi Islands day trip", "James Bond Island tour", "Elephant sanctuary visit", "Sunset beach dinner"]', true),
('jaipur', 'Jaipur', 'Edition 39 // Pink City', 'Pink city of maharajas and bazaars', 2400, 'India', 'Heritage', 'https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&q=80&w=600', '["Arrive at Jaipur Airport", "Heritage palace hotel", "Amber Fort morning tour", "Hawa Mahal photography", "Bazaar shopping walk", "Rajasthani folk evening"]', true),
('seville', 'Seville', 'Edition 40 // Flamenco Soul', 'Flamenco and orange-blossom nights', 2800, 'Spain', 'Heritage', 'https://images.unsplash.com/photo-1552394313-1e19cf1e49d1?auto=format&fit=crop&q=80&w=600', '["Arrive at Seville Airport", "Santa Cruz apartment", "Alcázar royal palace tour", "Flamenco show evening", "Tapas crawl in Triana", "Plaza de España sunset"]', true),
('new-york', 'New York', 'Edition 41 // Big Apple', 'Big Apple energy and skyline dreams', 4800, 'USA', 'Adventure', 'https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?auto=format&fit=crop&q=80&w=600', '["Arrive at JFK Airport", "Manhattan hotel check-in", "Statue of Liberty cruise", "Broadway show evening", "Central Park morning walk", "Top of the Rock sunset"]', true),
('tulum', 'Tulum', 'Edition 42 // Maya Coast', 'Mayan ruins and turquoise cenotes', 2900, 'Mexico', 'Escape', 'https://images.unsplash.com/photo-1504730653502-4f6028a8a3b8?auto=format&fit=crop&q=80&w=600', '["Arrive at Cancun Airport", "Tulum beachfront cabana", "Ruins sunrise visit", "Cenote swimming tour", "Sian Kaan biosphere reserve", "Beachfront yoga"]', true),
('rio-de-janeiro', 'Rio de Janeiro', 'Edition 43 // Marvelous City', 'Christ the Redeemer and samba soul', 3800, 'Brazil', 'Adventure', 'https://images.unsplash.com/photo-1483729558449-99ef09a8c325?auto=format&fit=crop&q=80&w=600', '["Arrive at Galeão Airport", "Copacabana hotel", "Christ the Redeemer visit", "Sugar Loaf cable car", "Ipanema beach day", "Samba night in Lapa"]', true),
('cusco', 'Cusco', 'Edition 44 // Inca Trail', 'Inca trails and Machu Picchu mists', 4400, 'Peru', 'Adventure', 'https://images.unsplash.com/photo-1587595431973-160d0d94add1?auto=format&fit=crop&q=80&w=600', '["Arrive at Cusco Airport", "Sacred Valley lodge", "Machu Picchu guided tour", "Rainbow Mountain hike", "Cusco city walking tour", "Pachamanca ceremonial dinner"]', true),
('buenos-aires', 'Buenos Aires', 'Edition 45 // Paris of South America', 'Tango and steak in the Paris of South America', 3200, 'Argentina', 'Heritage', 'https://images.unsplash.com/photo-1589909202802-8f4aadce65e9?auto=format&fit=crop&q=80&w=600', '["Arrive at Ezeiza Airport", "Palermo Soho loft", "Tango show evening", "La Boca colorful walk", "Parrilla steak dinner", "Recoleta cemetery tour"]', true),
('amazon', 'Amazon Rainforest', 'Edition 46 // Lung of the Planet', 'Rainforest immersion in the lungs of the planet', 5200, 'Brazil', 'Wild', 'https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&q=80&w=600', '["Arrive at Manaus Airport", "Amazon jungle lodge", "Canoe through flooded forest", "Jungle survival workshop", "Pink dolphin sighting", "Night jungle walk"]', true),
('sydney', 'Sydney', 'Edition 47 // Harbour City', 'Opera House and Bondi sun-kissed shores', 4600, 'Australia', 'Adventure', 'https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?auto=format&fit=crop&q=80&w=600', '["Arrive at Sydney Airport", "Circular Quay hotel", "Opera House backstage tour", "Bondi to Coogee coastal walk", "Sydney Harbour Bridge climb", "Ferry to Manly sunset"]', true),
('bora-bora', 'Bora Bora', 'Edition 48 // French Polynesia', 'Pearlescent lagoons and overwater bliss', 7200, 'French Polynesia', 'Escape', 'https://images.unsplash.com/photo-1583417319070-4a69db38a482?auto=format&fit=crop&q=80&w=600', '["Arrive at Tahiti Airport", "Air transfer to Bora Bora", "Overwater bungalow check-in", "Lagoon shark and ray swim", "4x4 island safari", "Sunset catamaran cruise"]', true),
('fiji', 'Fiji', 'Edition 49 // Bula Spirit', 'Bula spirit and coral garden wonders', 5400, 'Fiji', 'Escape', 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&q=80&w=600', '["Arrive at Nadi Airport", "Private island resort", "Coral reef snorkeling", "Fijian village visit", "Waterfall hike in Taveuni", "Kava ceremony experience"]', true),
('antarctica', 'Antarctica', 'Edition 50 // White Continent', 'The last great wilderness on Earth', 12000, 'Antarctica', 'Wild', 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?auto=format&fit=crop&q=80&w=600', '["Arrive at Ushuaia Argentina", "Expedition ship boarding", "Drake Passage crossing", "Penguin colony visit", "Iceberg kayaking", "Polar plunge ceremony"]', true)
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, edition = EXCLUDED.edition, description = EXCLUDED.description, price = EXCLUDED.price, country = EXCLUDED.country, vibe = EXCLUDED.vibe, img = EXCLUDED.img, steps = EXCLUDED.steps;

-- Seed sample trips
INSERT INTO trips (from_location, to_location, destination_id, departure_date, departure_time, max_capacity, booked_count, status) VALUES
('New York (JFK)', 'Naples (NAP)', 'amalfi', '2026-08-15', '08:30', 12, 5, 'scheduled'),
('Los Angeles (LAX)', 'Zurich (ZRH)', 'alps', '2026-09-01', '10:00', 10, 3, 'scheduled'),
('London (LHR)', 'Osaka (KIX)', 'kyoto', '2026-10-10', '14:00', 15, 2, 'scheduled'),
('Dubai (DXB)', 'Venice (VCE)', 'dolomites', '2026-07-20', '06:45', 8, 8, 'scheduled'),
('Paris (CDG)', 'Santorini (JTR)', 'santorini', '2026-08-05', '11:15', 10, 4, 'scheduled'),
('New York (JFK)', 'Reykjavik (KEF)', 'iceland', '2026-09-15', '22:00', 14, 7, 'scheduled'),
('London (LHR)', 'Marrakech (RAK)', 'marrakech', '2026-11-01', '07:30', 16, 10, 'scheduled'),
('Los Angeles (LAX)', 'Calgary (YYC)', 'banff', '2026-08-20', '09:00', 10, 1, 'scheduled'),
('Miami (MIA)', 'Punta Arenas (PUQ)', 'patagonia', '2026-12-01', '06:00', 8, 6, 'scheduled'),
('Auckland (AKL)', 'Queenstown (ZQN)', 'queenstown', '2026-10-05', '13:00', 12, 3, 'scheduled')
ON CONFLICT DO NOTHING;

-- Seed a sample booking for testing
INSERT INTO bookings (user_id, dest_id, guest_name, booking_date, guests, total, hotel, status, ref, from_location, to_location) VALUES
('00000000-0000-0000-0000-000000000000', 'amalfi', 'Test User', NOW(), 2, 8400, true, 'confirmed', 'NXG-TEST-001', 'New York (JFK)', 'Naples (NAP)')
ON CONFLICT DO NOTHING;
